import '../../../../utils/constants/enums.dart';
import '../../../../utils/constants/image_strings.dart';
import '../../models/attribute_model.dart';
import '../../models/banner_model.dart';
import '../../models/brand_model.dart';
import '../../models/category_model.dart';
import '../../models/product_attribute_model.dart';
import '../../models/product_model.dart';
import '../../models/product_variation_model.dart';

class TDummyData {
  /// -- Banners
  static final List<BannerModel> banners = [
    BannerModel(
      id: 'b1',
      imageUrl: TImages.banner1,
      title: 'Spring Sale',
      description: 'Up to 50% off on all items!',
      startDate: DateTime.now().subtract(const Duration(days: 5)),
      endDate: DateTime.now().add(const Duration(days: 10)),
      views: 0,
      clicks: 0,
      isActive: true,
      isFeatured: true,
      targetType: BannerTargetType.shopScreen,
      targetId: "",
      targetTitle: "",
      customUrl: "",
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updateAt: DateTime.now(),
    ),
    BannerModel(
      id: 'b2',
      imageUrl: TImages.banner2,
      title: 'Your Cart Awaits',
      description: 'Don’t miss what you left behind.',
      startDate: DateTime.now().subtract(const Duration(days: 2)),
      endDate: DateTime.now().add(const Duration(days: 5)),
      views: 0,
      clicks: 0,
      isActive: true,
      isFeatured: false,
      targetType: BannerTargetType.cart,
      targetId: "",
      targetTitle: "",
      customUrl: "",
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      updateAt: DateTime.now(),
    ),
    BannerModel(
      id: 'b3',
      imageUrl: TImages.banner3,
      title: 'Favorites Spotlight',
      description: 'See what you’ve favorited recently.',
      startDate: DateTime.now().subtract(const Duration(days: 1)),
      endDate: DateTime.now().add(const Duration(days: 7)),
      views: 0,
      clicks: 0,
      isActive: true,
      isFeatured: false,
      targetType: BannerTargetType.favouriteScreen,
      targetId: "",
      targetTitle: "",
      customUrl: "",
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updateAt: DateTime.now(),
    ),
    BannerModel(
      id: 'b4',
      imageUrl: TImages.banner4,
      title: 'App Settings Tips',
      description: 'Customize your experience in settings.',
      startDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 14)),
      views: 0,
      clicks: 0,
      isActive: true,
      isFeatured: false,
      targetType: BannerTargetType.settingScreen,
      targetId: "",
      targetTitle: "",
      customUrl: "",
      createdAt: DateTime.now(),
      updateAt: DateTime.now(),
    ),
    BannerModel(
      id: 'b5',
      imageUrl: TImages.banner5,
      title: 'Shop the Collection',
      description: 'New arrivals just launched!',
      startDate: DateTime.now().subtract(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 4)),
      views: 0,
      clicks: 0,
      isActive: true,
      isFeatured: true,
      targetType: BannerTargetType.categoryScreen,
      targetId: 'cat_123',
      targetTitle: 'New Arrivals',
      customUrl: "",
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updateAt: DateTime.now(),
    ),
    BannerModel(
      id: 'b6',
      imageUrl: TImages.banner6,
      title: 'Welcome, User!',
      description: 'Visit your profile to update info.',
      startDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 30)),
      views: 0,
      clicks: 0,
      isActive: true,
      isFeatured: false,
      targetType: BannerTargetType.profile,
      targetId: 'user_001',
      targetTitle: 'Your Profile',
      customUrl: "",
      createdAt: DateTime.now(),
      updateAt: DateTime.now(),
    ),
    BannerModel(
      id: 'b7',
      imageUrl: TImages.banner8,
      title: 'Limited-Time Offer',
      description: 'Click to learn more.',
      startDate: DateTime.now().subtract(const Duration(days: 10)),
      endDate: DateTime.now().subtract(const Duration(days: 1)),
      views: 0,
      clicks: 0,
      isActive: false,
      isFeatured: true,
      targetType: BannerTargetType.customUrl,
      targetId: "",
      targetTitle: 'Flash Deal',
      customUrl: 'https://yourapp.com/flash-deal',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updateAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];

  /// -- List of all Categories (with linked BrandModel objects)
  static final List<CategoryModel> categories = [
    // Top‐level
    CategoryModel(
      id: '1',
      name: 'Sports',
      imageURL: TImages.sportIcon,
      parentId: '',
      isActive: true,
      isFeatured: true,
      priority: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      numberOfProducts: 120,
      viewCount: 450,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['1', '2', '3', '4'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '5',
      name: 'Furniture',
      imageURL: TImages.furnitureIcon,
      parentId: '',
      isActive: true,
      isFeatured: true,
      priority: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 28)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      numberOfProducts: 80,
      viewCount: 300,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['9', '8'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '2',
      name: 'Electronics',
      imageURL: TImages.electronicsIcon,
      parentId: '',
      isActive: true,
      isFeatured: true,
      priority: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      numberOfProducts: 200,
      viewCount: 800,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['5', '7', '10', '8'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '3',
      name: 'Clothes',
      imageURL: TImages.clothIcon,
      parentId: '',
      isActive: true,
      isFeatured: true,
      priority: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      numberOfProducts: 150,
      viewCount: 600,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['6'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '4',
      name: 'Animals',
      imageURL: TImages.animalIcon,
      parentId: '',
      isActive: true,
      isFeatured: true,
      priority: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      numberOfProducts: 50,
      viewCount: 200,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: [],
    ),
    CategoryModel(
      id: '6',
      name: 'Shoes',
      imageURL: TImages.shoeIcon,
      parentId: '',
      isActive: true,
      isFeatured: true,
      priority: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      numberOfProducts: 90,
      viewCount: 350,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['1', '2', '3'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '7',
      name: 'Cosmetics',
      imageURL: TImages.cosmeticsIcon,
      parentId: '',
      isActive: true,
      isFeatured: true,
      priority: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      numberOfProducts: 60,
      viewCount: 250,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: [],
    ),
    CategoryModel(
      id: '17',
      name: 'Jewelery',
      imageURL: TImages.jeweleryIcon,
      parentId: '',
      isActive: true,
      isFeatured: true,
      priority: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      numberOfProducts: 40,
      viewCount: 180,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: [],
    ),

    // Sub‐categories of Sports (parentId = '1')
    CategoryModel(
      id: '8',
      name: 'Sport Shoes',
      imageURL: TImages.sportIcon,
      parentId: '1',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      numberOfProducts: 45,
      viewCount: 120,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['1', '2', '3'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '9',
      name: 'Track suits',
      imageURL: TImages.sportIcon,
      parentId: '1',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      numberOfProducts: 30,
      viewCount: 90,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['1', '2'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '10',
      name: 'Sports Equipments',
      imageURL: TImages.sportIcon,
      parentId: '1',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      numberOfProducts: 55,
      viewCount: 140,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: [],
    ),

    // Sub‐categories of Furniture (parentId = '5')
    CategoryModel(
      id: '11',
      name: 'Bedroom furniture',
      imageURL: TImages.furnitureIcon,
      parentId: '5',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 9)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      numberOfProducts: 25,
      viewCount: 75,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['9'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '12',
      name: 'Kitchen furniture',
      imageURL: TImages.furnitureIcon,
      parentId: '5',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      numberOfProducts: 20,
      viewCount: 60,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['9', '8'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '13',
      name: 'Office furniture',
      imageURL: TImages.furnitureIcon,
      parentId: '5',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      numberOfProducts: 35,
      viewCount: 110,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['9', '8'].contains(b.id)).toList(),
    ),

    // Sub‐categories of Electronics (parentId = '2')
    CategoryModel(
      id: '14',
      name: 'Laptop',
      imageURL: TImages.electronicsIcon,
      parentId: '2',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      numberOfProducts: 70,
      viewCount: 260,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['5', '10', '8'].contains(b.id)).toList(),
    ),
    CategoryModel(
      id: '15',
      name: 'Mobile',
      imageURL: TImages.electronicsIcon,
      parentId: '2',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      numberOfProducts: 90,
      viewCount: 310,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['5', '7', '10'].contains(b.id)).toList(),
    ),

    // Sub‐categories of Clothes (parentId = '3')
    CategoryModel(
      id: '16',
      name: 'Shirts',
      imageURL: TImages.clothIcon,
      parentId: '3',
      isActive: true,
      isFeatured: false,
      priority: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      numberOfProducts: 50,
      viewCount: 180,
      createdBy: 'admin',
      updatedBy: 'admin',
      // brands: brands.where((b) => ['6'].contains(b.id)).toList(),
    ),
  ];

  /// -- List of all Brands (with linked CategoryModel objects)
  static final List<BrandModel> brands = [
    BrandModel(
      id: '1',
      imageURL: TImages.nikeLogo,
      name: 'Nike',
      isFeatured: true,
      isActive: true,
      productsCount: 265,
      viewCount: 1025,
      createdAt: DateTime.now().subtract(const Duration(days: 40)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      // categories: categories.where((c) => ['1', '6', '8', '9'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '2',
      imageURL: TImages.adidasLogo,
      name: 'Adidas',
      isFeatured: true,
      isActive: true,
      productsCount: 95,
      viewCount: 410,
      createdAt: DateTime.now().subtract(const Duration(days: 35)),
      updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      // categories: categories.where((c) => ['1', '6', '8', '9'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '3',
      imageURL: TImages.jordanLogo,
      name: 'Jordan',
      isFeatured: true,
      isActive: true,
      productsCount: 36,
      viewCount: 150,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      // categories: categories.where((c) => ['1', '6', '8'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '4',
      imageURL: TImages.pumaLogo,
      name: 'Puma',
      isFeatured: true,
      isActive: true,
      productsCount: 65,
      viewCount: 280,
      createdAt: DateTime.now().subtract(const Duration(days: 28)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      // categories: categories.where((c) => ['1'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '5',
      imageURL: TImages.appleLogo,
      name: 'Apple',
      isFeatured: true,
      isActive: true,
      productsCount: 16,
      viewCount: 90,
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      // categories: categories.where((c) => ['2', '14', '15'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '6',
      imageURL: TImages.zaraLogo,
      name: 'ZARA',
      isFeatured: true,
      isActive: true,
      productsCount: 36,
      viewCount: 130,
      createdAt: DateTime.now().subtract(const Duration(days: 22)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      // categories: categories.where((c) => ['3', '16'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '7',
      imageURL: TImages.electronicsIcon,
      name: 'Samsung',
      isFeatured: false,
      isActive: true,
      productsCount: 36,
      viewCount: 115,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      // categories: categories.where((c) => ['2', '15'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '8',
      imageURL: TImages.kenwoodLogo,
      name: 'Kenwood',
      isFeatured: false,
      isActive: true,
      productsCount: 36,
      viewCount: 70,
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      // categories: categories.where((c) => ['5', '12', '13', '14'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '9',
      imageURL: TImages.ikeaLogo,
      name: 'IKEA',
      isFeatured: false,
      isActive: true,
      productsCount: 36,
      viewCount: 95,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      // categories: categories.where((c) => ['5', '11', '12', '13'].contains(c.id)).toList(),
    ),
    BrandModel(
      id: '10',
      imageURL: TImages.acerlogo,
      name: 'Acer',
      isFeatured: false,
      isActive: true,
      productsCount: 36,
      viewCount: 85,
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      // categories: categories.where((c) => ['2', '14', '15'].contains(c.id)).toList(),
    ),
  ];

  ///
  static final List<AttributeModel> attributes = [
    // Sizes
    AttributeModel(
      id: 'baQDeu1mZmc0ipGCh9vc',
      name: 'Sizes',
      attributeValues: ['Small', 'Medium', 'Large', 'X Large', 'XX Large'],
      isActive: true,
      isSearchable: true,
      isFilterable: true,
      isColorAttribute: false,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now(),
    ),

    // Colors
    AttributeModel(
      id: 'jve1tbtbjTetOYK9MF46',
      name: 'Colors',
      attributeValues: [
        '4294921035',
        '4294945355',
        '4294965323',
        '4289265483',
        '4283170651',
        '4283170770',
        '4283158527',
        '4283130367',
        '4287581183',
        '4293544959',
        '4294921127',
        '4278190080',
        '4294967295',
        '4287137928'
      ],
      isActive: true,
      isSearchable: false,
      isFilterable: true,
      isColorAttribute: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now(),
    ),

    // Materials
    AttributeModel(
      id: 'N6jfoeR5aG8FgZktmRWs',
      name: 'Materials',
      attributeValues: ['Cotton', 'Polyester', 'Leather', 'Denim', 'Silk', 'Wool'],
      isActive: true,
      isSearchable: true,
      isFilterable: true,
      isColorAttribute: false,
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      updatedAt: DateTime.now(),
    ),
  ];

  // Add all product description format like [{"insert":"This is a Product description for 4 Color collar t-shirt dry fit. There are more things that can be added but it’s just a demo and nothing else.\n"}]
  /// -- List of all Products
  static final List<ProductModel> products = [
    ProductModel(
      id: '00001',
      title: 'Green Nike sports shoe',
      lowerTitle: 'green nike sports shoe',
      description: [
        {"insert": "Green Nike sports shoe"}
      ].toString(),
      sku: 'ABR4568',
      price: 135,
      salePrice: null,
      thumbnail: TImages.productImage1,
      images: [TImages.productImage1, TImages.productImage23, TImages.productImage21, TImages.productImage9],
      productType: ProductType.variable,
      stock: 50,
      soldQuantity: 0,
      // brand: BrandModel(
      //   id: 'BDb586QxgEvn5qml59qG',
      //   imageURL:
      //       "https://firebasestorage.googleapis.com/v0/b/codingwitht-c6d0f.appspot.com/o/Brands%2Fpngegg%20(1).png?alt=media&token=347fee17-38a5-48ca-8998-35b184ba476e",
      //   name: 'Adidas',
      // ),
      tags: ['sports', 'shoes', 'nike', 'sneakers'],
      // categories: [categories.firstWhere((c) => c.id == '1')],
      // categoryIds: ['1'],
      attributes: [
        ProductAttributeModel(id: '', attributeId: 'yLUNuVvt0ufiwJRd88hD', name: 'Colors', values: ['4294965323', '4289265483'], isColorAttribute: true),
        ProductAttributeModel(id: '', attributeId: 'MelWC2h0BeaCRDQGiU9t', name: 'Sizes', values: ['Small', 'Medium'], isColorAttribute: false),
      ],
      variations: [
        ProductVariationModel(
          id: 'VAR-15223265',
          stock: 34,
          price: 134,
          salePrice: 122.6,
          image: TImages.productImage1,
          description: 'This is a Small Product Nike sports...',
          attributeValues: {'Colors': '4294965323', 'Sizes': 'Small'},
          sku: 'ABR4568-1',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: 'VAR-2787157',
          stock: 34,
          price: 134,
          salePrice: 122.6,
          image: TImages.productImage1,
          description: 'This is a Medium Product Nike sports...',
          attributeValues: {'Colors': '4294965323', 'Sizes': 'Medium'},
          sku: 'ABR4568-2',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: 'VAR-36526815671',
          stock: 34,
          price: 134,
          salePrice: 121.6,
          image: TImages.productImage1,
          description: 'This is a Small Product Nike sports...',
          attributeValues: {'Colors': '4289265483', 'Sizes': 'Small'},
          sku: 'ABR4568-3',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: 'VAR-47828954',
          stock: 34,
          price: 134,
          salePrice: 112.6,
          image: TImages.productImage1,
          description: 'This is a Medium Product Nike sports...',
          attributeValues: {'Colors': '4289265483', 'Sizes': 'Medium'},
          sku: 'ABR4568-4',
          soldQuantity: 0,
        ),
      ],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: false,
      saleEndDate: null,
      saleStartDate: null,
    ),

    ProductModel(
      id: '00002',
      title: 'Blue T-shirt for all ages',
      lowerTitle: 'blue t-shirt for all ages',
      description: [
        {"insert": "This is a Product description for Blue Nike Sleeve less vest. There are more things that can be added but I am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 35,
      salePrice: 30,
      thumbnail: TImages.productImage69,
      images: [
        TImages.productImage68,
        TImages.productImage69,
        TImages.productImage5,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['tshirt', 'blue', 'shirt', 'unisex'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Sizes',
          values: ['Small', 'Medium', 'Large'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Colors',
          values: ['4294921035', '4294945355', '4294965323'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    ProductModel(
      id: '00003',
      title: 'Leather brown Jacket',
      lowerTitle: 'leather brown jacket',
      description: [
        {"insert": "This is a Product description for Leather brown Jacket. There are more things that can be added but I am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 38000,
      salePrice: 30,
      thumbnail: TImages.productImage64,
      images: [
        TImages.productImage64,
        TImages.productImage65,
        TImages.productImage66,
        TImages.productImage67,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['jacket', 'leather', 'brown'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Sizes',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    ProductModel(
      id: '00004',
      title: '4 Color collar t-shirt dry fit',
      lowerTitle: '4 color collar t-shirt dry fit',
      description: [
        {"insert": "This is a Product description for 4 Color collar t-shirt dry fit. There are more things that can be added but it’s just a demo and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 135,
      salePrice: 30,
      thumbnail: TImages.productImage60,
      images: [
        TImages.productImage60,
        TImages.productImage61,
        TImages.productImage62,
        TImages.productImage63,
      ],
      productType: ProductType.variable,
      stock: 15,
      soldQuantity: 0,
      tags: ['tshirt', 'dry-fit', 'collar', '4-color'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Red', 'Yellow', 'Green', 'Blue'],
          isColorAttribute: true,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Size',
          values: ['EU 30', 'EU 32', 'EU 34'],
          isColorAttribute: false,
        ),
      ],
      variations: [
        ProductVariationModel(
          id: '1',
          stock: 34,
          price: 134,
          salePrice: 122.6,
          image: TImages.productImage60,
          description: [
            {"insert": "This is a Product description for 4 Color collar t-shirt dry fit."}
          ].toString(),
          attributeValues: {'Color': 'Red', 'Size': 'EU 34'},
          sku: 'ABR4568-1',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 132,
          salePrice: 0.0,
          image: TImages.productImage60,
          description: "".toString(),
          attributeValues: {'Color': 'Red', 'Size': 'EU 32'},
          sku: 'ABR4568-2',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '3',
          stock: 0,
          price: 234,
          salePrice: 0.0,
          image: TImages.productImage61,
          description: "".toString(),
          attributeValues: {'Color': 'Yellow', 'Size': 'EU 34'},
          sku: 'ABR4568-3',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '4',
          stock: 222,
          price: 232,
          salePrice: 0.0,
          image: TImages.productImage61,
          description: "".toString(),
          attributeValues: {'Color': 'Yellow', 'Size': 'EU 32'},
          sku: 'ABR4568-4',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '5',
          stock: 0,
          price: 334,
          salePrice: 0.0,
          image: TImages.productImage62,
          description: "".toString(),
          attributeValues: {'Color': 'Green', 'Size': 'EU 34'},
          sku: 'ABR4568-5',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '6',
          stock: 11,
          price: 332,
          salePrice: 0.0,
          image: TImages.productImage62,
          description: "".toString(),
          attributeValues: {'Color': 'Green', 'Size': 'EU 30'},
          sku: 'ABR4568-6',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '7',
          stock: 0,
          price: 334,
          salePrice: 0.0,
          image: TImages.productImage63,
          description: "".toString(),
          attributeValues: {'Color': 'Blue', 'Size': 'EU 30'},
          sku: 'ABR4568-7',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '8',
          stock: 11,
          price: 332,
          salePrice: 0.0,
          image: TImages.productImage63,
          description: "".toString(),
          attributeValues: {'Color': 'Blue', 'Size': 'EU 34'},
          sku: 'ABR4568-8',
          soldQuantity: 0,
        ),
      ],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    /// Products after banner
    ProductModel(
      id: '00005',
      title: 'Nike Air Jordon Shoes',
      lowerTitle: 'nike air jordon shoes',
      description: [
        {"insert": "Nike Air Jordon Shoes for running. Quality product, Long Lasting"}
      ].toString(),
      sku: 'ABR4568',
      price: 35,
      salePrice: 30,
      thumbnail: TImages.productImage10,
      images: [
        TImages.productImage7,
        TImages.productImage8,
        TImages.productImage9,
        TImages.productImage10,
      ],
      productType: ProductType.variable,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'air', 'jordon', 'shoes', 'running'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Orange', 'Black', 'Brown'],
          isColorAttribute: true,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Size',
          values: ['EU 30', 'EU 32', 'EU 34'],
          isColorAttribute: false,
        ),
      ],
      variations: [
        ProductVariationModel(
          id: '1',
          stock: 16,
          price: 36,
          salePrice: 12.6,
          image: TImages.productImage8,
          description: [
            {"insert": "Flutter is Google’s mobile UI open source framework to build high-quality native (super fast) interfaces for iOS and Android apps with the unified codebase."}
          ].toString(),
          attributeValues: {'Color': 'Orange', 'Size': 'EU 34'},
          sku: 'ABR4568-1',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 35,
          salePrice: 0.0,
          image: TImages.productImage7,
          description: "".toString(),
          attributeValues: {'Color': 'Black', 'Size': 'EU 32'},
          sku: 'ABR4568-2',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '3',
          stock: 14,
          price: 34,
          salePrice: 0.0,
          image: TImages.productImage9,
          description: "".toString(),
          attributeValues: {'Color': 'Brown', 'Size': 'EU 34'},
          sku: 'ABR4568-3',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '4',
          stock: 13,
          price: 33,
          salePrice: 0.0,
          image: TImages.productImage7,
          description: "".toString(),
          attributeValues: {'Color': 'Black', 'Size': 'EU 34'},
          sku: 'ABR4568-4',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '5',
          stock: 12,
          price: 32,
          salePrice: 0.0,
          image: TImages.productImage9,
          description: "".toString(),
          attributeValues: {'Color': 'Brown', 'Size': 'EU 32'},
          sku: 'ABR4568-5',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '6',
          stock: 11,
          price: 31,
          salePrice: 0.0,
          image: TImages.productImage8,
          description: "".toString(),
          attributeValues: {'Color': 'Orange', 'Size': 'EU 32'},
          sku: 'ABR4568-6',
          soldQuantity: 0,
        ),
      ],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    ProductModel(
      id: '00006',
      title: 'SAMSUNG Galaxy S9 (Pink, 64 GB)  (4 GB RAM)',
      lowerTitle: 'samsung galaxy s9 (pink, 64 gb) (4 gb ram)',
      description: [
        {"insert": "SAMSUNG Galaxy S9 (Pink, 64 GB)  (4 GB RAM), Long Battery timing"}
      ].toString(),
      sku: 'ABR4568',
      price: 750,
      salePrice: 650,
      thumbnail: TImages.productImage11,
      images: [
        TImages.productImage11,
        TImages.productImage12,
        TImages.productImage13,
        TImages.productImage12,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['samsung', 'galaxy', 's9', 'pink', '64gb', '4gb'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Sizes',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    ProductModel(
      id: '00007',
      title: 'TOMI Dog food',
      lowerTitle: 'tomi dog food',
      description: [
        {"insert": "This is a Product description for TOMI Dog food. There are more things that can be added but I am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 20,
      salePrice: 10,
      thumbnail: TImages.productImage18,
      images: [TImages.productImage18],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['tomi', 'dog', 'food', 'pet'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    //00008 after 040
    ProductModel(
      id: '00009',
      title: 'Nike Air Jordon 19 Blue',
      lowerTitle: 'nike air jordon 19 blue',
      description: [
        {"insert": "This is a Product description for Nike Air Jordon. There are more things that can be added but I am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 400,
      salePrice: 200,
      thumbnail: TImages.productImage19,
      images: [
        TImages.productImage19,
        TImages.productImage20,
        TImages.productImage21,
        TImages.productImage22,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'air', 'jordon', 'blue'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    // Product 00010
    ProductModel(
      id: '00010',
      title: 'Nike Air Jordon 6 Orange',
      lowerTitle: 'nike air jordon 6 orange',
      description: [
        {"insert": "This is a Product description for Nike Air Jordon. There are more things that can be added but I am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 400,
      salePrice: 0.0,
      thumbnail: TImages.productImage20,
      images: [
        TImages.productImage20,
        TImages.productImage23,
        TImages.productImage21,
        TImages.productImage22,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'air', 'jordon', 'orange'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Sizes',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00011
    ProductModel(
      id: '00011',
      title: 'Nike Air Max Red & Black',
      lowerTitle: 'nike air max red & black',
      description: [
        {"insert": "This is a Product description for Nike Air Max. There are more things that can be added but I am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 600,
      salePrice: 400,
      thumbnail: TImages.productImage21,
      images: [
        TImages.productImage21,
        TImages.productImage20,
        TImages.productImage19,
        TImages.productImage22,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'air', 'max', 'red', 'black'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Sizes',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00012
    ProductModel(
      id: '00012',
      title: 'Nike Basketball shoes Black & Green',
      lowerTitle: 'nike basketball shoes black & green',
      description: [
        {"insert": "This is a Product description for Nike Basketball shoes. There are more things that can be added but I am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 600,
      salePrice: 400,
      thumbnail: TImages.productImage22,
      images: [
        TImages.productImage22,
        TImages.productImage20,
        TImages.productImage21,
        TImages.productImage23,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'basketball', 'shoes', 'black', 'green'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Sizes',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00013
    ProductModel(
      id: '00013',
      title: 'Nike wild horse shoes',
      lowerTitle: 'nike wild horse shoes',
      description: [
        {"insert": "This is a Product description for Nike wild horse shoes. There are more things that can be added but I am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 600,
      salePrice: 400,
      thumbnail: TImages.productImage23,
      images: [
        TImages.productImage23,
        TImages.productImage20,
        TImages.productImage21,
        TImages.productImage22,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'wild', 'horse', 'shoes'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Sizes',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    //Track suits
    // Product 00014
    ProductModel(
      id: '00014',
      title: 'Nike Track suit red',
      lowerTitle: 'nike track suit red',
      description: [
        {"insert": "This is a Product description for Nike Track suit red. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 500,
      salePrice: 0.0,
      thumbnail: TImages.productImage26,
      images: [
        TImages.productImage26,
        TImages.productImage24,
        TImages.productImage25,
        TImages.productImage27,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'track', 'suit', 'red'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00015
    ProductModel(
      id: '00015',
      title: 'Nike Track suit Black',
      lowerTitle: 'nike track suit black',
      description: [
        {"insert": "This is a Product description for Nike Track suit Black. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 200,
      salePrice: 0.0,
      thumbnail: TImages.productImage24,
      images: [
        TImages.productImage24,
        TImages.productImage26,
        TImages.productImage25,
        TImages.productImage27,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'track', 'suit', 'black'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00016
    ProductModel(
      id: '00016',
      title: 'Nike Track suit Blue',
      lowerTitle: 'nike track suit blue',
      description: [
        {"insert": "This is a Product description for Nike Track suit Blue. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 100,
      salePrice: 0.0,
      thumbnail: TImages.productImage25,
      images: [
        TImages.productImage25,
        TImages.productImage24,
        TImages.productImage26,
        TImages.productImage27,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'track', 'suit', 'blue'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00017
    ProductModel(
      id: '00017',
      title: 'Nike Track suit Parrot Green',
      lowerTitle: 'nike track suit parrot green',
      description: [
        {"insert": "This is a Product description for Nike Track suit Parrot Green. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 350,
      salePrice: 0.0,
      thumbnail: TImages.productImage27,
      images: [
        TImages.productImage27,
        TImages.productImage24,
        TImages.productImage25,
        TImages.productImage26,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['nike', 'track', 'suit', 'parrot', 'green'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    //Sports Equipments
    // Product 00018
    ProductModel(
      id: '00018',
      title: 'Adidas Football',
      lowerTitle: 'adidas football',
      description: [
        {"insert": "This is a Product description for Football. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 40,
      salePrice: 0.0,
      thumbnail: TImages.productImage28,
      images: [
        TImages.productImage28,
        TImages.productImage29,
        TImages.productImage30,
        TImages.productImage31,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['adidas', 'football'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00019
    ProductModel(
      id: '00019',
      title: 'Baseball Bat',
      lowerTitle: 'baseball bat',
      description: [
        {"insert": "This is a Product description for Baseball Bat. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 30,
      salePrice: 0.0,
      thumbnail: TImages.productImage29,
      images: [
        TImages.productImage29,
        TImages.productImage28,
        TImages.productImage30,
        TImages.productImage31,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['baseball', 'bat'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00020
    ProductModel(
      id: '00020',
      title: 'Cricket Bat',
      lowerTitle: 'cricket bat',
      description: [
        {"insert": "This is a Product description for Cricket Bat. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 25,
      salePrice: 0.0,
      thumbnail: TImages.productImage30,
      images: [
        TImages.productImage30,
        TImages.productImage29,
        TImages.productImage28,
        TImages.productImage31,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['cricket', 'bat'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00021
    ProductModel(
      id: '00021',
      title: 'Tennis Racket',
      lowerTitle: 'tennis racket',
      description: [
        {"insert": "This is a Product description for Tennis Racket. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 54,
      salePrice: 0.0,
      thumbnail: TImages.productImage31,
      images: [
        TImages.productImage31,
        TImages.productImage29,
        TImages.productImage30,
        TImages.productImage28,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['tennis', 'racket'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    ///Furniture
    //bedroom
    // Product 00022
    ProductModel(
      id: '00022',
      title: 'Pure Wooden Bed',
      lowerTitle: 'pure wooden bed',
      description: [
        {"insert": "Flutter is Google’s mobile UI open source framework to build high-quality native (super fast) interfaces for iOS and Android apps with the unified codebase."}
      ].toString(),
      sku: 'ABR4568',
      price: 950,
      salePrice: 600,
      thumbnail: TImages.productImage32,
      images: [
        TImages.productImage43,
        TImages.productImage44,
        TImages.productImage45,
        TImages.productImage46,
      ],
      productType: ProductType.variable,
      stock: 15,
      soldQuantity: 0,
      tags: ['wooden', 'bed', 'furniture'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Black', 'Grey', 'Brown'],
          isColorAttribute: true,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Size',
          values: ['EU 30', 'EU 32', 'EU 34'],
          isColorAttribute: false,
        ),
      ],
      variations: [
        ProductVariationModel(
          id: '1',
          stock: 16,
          price: 36,
          salePrice: 12.6,
          image: TImages.productImage32,
          description: [
            {"insert": "Flutter is Google’s mobile UI open source framework to build high-quality native (super fast) interfaces for iOS and Android apps with the unified codebase."}
          ].toString(),
          attributeValues: {'Color': 'Brown', 'Size': 'EU 34'},
          sku: 'ABR4568-1',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 35,
          salePrice: 0.0,
          image: TImages.productImage45,
          description: "".toString(),
          attributeValues: {'Color': 'Brown', 'Size': 'EU 32'},
          sku: 'ABR4568-2',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '3',
          stock: 14,
          price: 34,
          salePrice: 0.0,
          image: TImages.productImage46,
          description: "".toString(),
          attributeValues: {'Color': 'Brown', 'Size': 'EU 30'},
          sku: 'ABR4568-3',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '4',
          stock: 13,
          price: 33,
          salePrice: 0.0,
          image: TImages.productImage43,
          description: "".toString(),
          attributeValues: {'Color': 'Black', 'Size': 'EU 32'},
          sku: 'ABR4568-4',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '5',
          stock: 12,
          price: 32,
          salePrice: 0.0,
          image: TImages.productImage43,
          description: "".toString(),
          attributeValues: {'Color': 'Black', 'Size': 'EU 34'},
          sku: 'ABR4568-5',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '6',
          stock: 11,
          price: 31,
          salePrice: 0.0,
          image: TImages.productImage44,
          description: "".toString(),
          attributeValues: {'Color': 'Grey', 'Size': 'EU 32'},
          sku: 'ABR4568-6',
          soldQuantity: 0,
        ),
      ],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00023
    ProductModel(
      id: '00023',
      title: 'Side Table Lamp',
      lowerTitle: 'side table lamp',
      description: [
        {"insert": "This is a Product description for Side Table Lamp. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 25,
      salePrice: 0.0,
      thumbnail: TImages.productImage33,
      images: [TImages.productImage33],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['side', 'table', 'lamp', 'home'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00024
    ProductModel(
      id: '00024',
      title: 'Bedroom Sofa',
      lowerTitle: 'bedroom sofa',
      description: [
        {"insert": "This is a Product description for Bedroom Sofa. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 25,
      salePrice: 0.0,
      thumbnail: TImages.productImage34,
      images: [TImages.productImage34],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['bedroom', 'sofa', 'furniture'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00025
    ProductModel(
      id: '00025',
      title: 'Wardrobe for Bedroom',
      lowerTitle: 'wardrobe for bedroom',
      description: [
        {"insert": "This is a Product description for Bedroom Wardrobe. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 56,
      salePrice: 0.0,
      thumbnail: TImages.productImage35,
      images: [TImages.productImage35],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['wardrobe', 'bedroom', 'furniture'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    //Kitchen
    // Product 00026
    ProductModel(
      id: '00026',
      title: 'Kitchen Counter',
      lowerTitle: 'kitchen counter',
      description: [
        {"insert": "This is a Product description for Kitchen Counter. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 1012,
      salePrice: 0.0,
      thumbnail: TImages.productImage36,
      images: [TImages.productImage36],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['kitchen', 'counter', 'furniture'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Sizes
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Colors
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00027
    ProductModel(
      id: '00027',
      title: 'Dinning Table',
      lowerTitle: 'dinning table',
      description: [
        {"insert": "This is a Product description for Dinning Table. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 1012,
      salePrice: 0.0,
      thumbnail: TImages.productImage37,
      images: [TImages.productImage37],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['dinning', 'table', 'furniture'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00028
    ProductModel(
      id: '00028',
      title: 'Refrigerator',
      lowerTitle: 'refrigerator',
      description: [
        {"insert": "This is a Product description for Refrigerator. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 987,
      salePrice: 0.0,
      thumbnail: TImages.productImage38,
      images: [TImages.productImage38],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['refrigerator', 'appliance'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00029
    ProductModel(
      id: '00029',
      title: 'Office Chair Red',
      lowerTitle: 'office chair red',
      description: [
        {"insert": "This is a Product description for Office Chair. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 150,
      salePrice: 0.0,
      thumbnail: TImages.productImage39,
      images: [TImages.productImage39],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['office', 'chair', 'red'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00030
    ProductModel(
      id: '00030',
      title: 'Office Chair White',
      lowerTitle: 'office chair white',
      description: [
        {"insert": "This is a Product description for Office Chair. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 140,
      salePrice: 0.0,
      thumbnail: TImages.productImage40,
      images: [TImages.productImage40],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['office', 'chair', 'white'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00031
    ProductModel(
      id: '00031',
      title: 'Office Desk Red',
      lowerTitle: 'office desk red',
      description: [
        {"insert": "This is a Product description for Office Desk. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 360,
      salePrice: 0.0,
      thumbnail: TImages.productImage41,
      images: [TImages.productImage41],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['office', 'desk', 'red'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00032
    ProductModel(
      id: '00032',
      title: 'Office Desk brown',
      lowerTitle: 'office desk brown',
      description: [
        {"insert": "This is a Product description for Office Desk. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 400,
      salePrice: 0.0,
      thumbnail: TImages.productImage42,
      images: [TImages.productImage42],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['office', 'desk', 'brown'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

    ///Electronics
    //Laptops
    // Product 00033
    ProductModel(
      id: '00033',
      title: 'Acer Laptop RAM 8gb to 16gb 512gb to 2tb',
      lowerTitle: 'acer laptop ram 8gb to 16gb 512gb to 2tb',
      description: [
        {"insert": "This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 950,
      salePrice: 800,
      thumbnail: TImages.productImage56,
      images: [
        TImages.productImage56,
        TImages.productImage47,
        TImages.productImage57,
        TImages.productImage58,
      ],
      productType: ProductType.variable,
      stock: 15,
      soldQuantity: 0,
      tags: ['acer', 'laptop', 'ram', 'ssd'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Ram
          name: 'Ram',
          values: ['6', '8', '16'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // SSD
          name: 'SSD',
          values: ['512', '1 tb', '2 tb'],
          isColorAttribute: false,
        ),
      ],
      variations: [
        ProductVariationModel(
          id: '1',
          stock: 16,
          price: 400,
          salePrice: 350,
          image: TImages.productImage56,
          description: [
            {"insert": "This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else."}
          ].toString(),
          attributeValues: {'Ram': '6', 'SSD': '512'},
          sku: 'ABR4568-1',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 450,
          salePrice: 0.0,
          image: TImages.productImage47,
          description: "".toString(),
          attributeValues: {'Ram': '8', 'SSD': '512'},
          sku: 'ABR4568-2',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '3',
          stock: 14,
          price: 470,
          salePrice: 0.0,
          image: TImages.productImage59,
          description: "".toString(),
          attributeValues: {'Ram': '8', 'SSD': '1 tb'},
          sku: 'ABR4568-3',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '4',
          stock: 13,
          price: 500,
          salePrice: 0.0,
          image: TImages.productImage58,
          description: "".toString(),
          attributeValues: {'Ram': '16', 'SSD': '512'},
          sku: 'ABR4568-4',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '5',
          stock: 12,
          price: 650,
          salePrice: 0.0,
          image: TImages.productImage57,
          description: "".toString(),
          attributeValues: {'Ram': '16', 'SSD': '1 tb'},
          sku: 'ABR4568-5',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '6',
          stock: 11,
          price: 800,
          salePrice: 0.0,
          image: TImages.productImage59,
          description: "".toString(),
          attributeValues: {'Ram': '16', 'SSD': '2 tb'},
          sku: 'ABR4568-6',
          soldQuantity: 0,
        ),
      ],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00034
    ProductModel(
      id: '00034',
      title: 'Acer Laptop 6gb 1tb',
      lowerTitle: 'acer laptop 6gb 1tb',
      description: [
        {"insert": "This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 400,
      salePrice: 0.0,
      thumbnail: TImages.productImage48,
      images: [TImages.productImage48],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['acer', 'laptop'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Size
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Color
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00035
    ProductModel(
      id: '00035',
      title: 'Acer Laptop 6gb 500Gb',
      lowerTitle: 'acer laptop 6gb 500gb',
      description: [
        {"insert": "This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 400,
      salePrice: 0.0,
      thumbnail: TImages.productImage49,
      images: [TImages.productImage49],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['acer', 'laptop'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00036
    ProductModel(
      id: '00036',
      title: 'Acer Laptop 4gb 500Gb',
      lowerTitle: 'acer laptop 4gb 500gb',
      description: [
        {"insert": "This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 400,
      salePrice: 0.0,
      thumbnail: TImages.productImage50,
      images: [TImages.productImage50],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['acer', 'laptop'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00037
    ProductModel(
      id: '00037',
      title: 'Iphone 13 pro 512gb',
      lowerTitle: 'iphone 13 pro 512gb',
      description: [
        {"insert": "This is a Product description for Iphone. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 999,
      salePrice: 0.0,
      thumbnail: TImages.productImage51,
      images: [TImages.productImage51],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['iphone', '13', 'pro', '512gb'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00038
    ProductModel(
      id: '00038',
      title: 'Iphone 14 pro 512gb',
      lowerTitle: 'iphone 14 pro 512gb',
      description: [
        {"insert": "This is a Product description for Iphone. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 999,
      salePrice: 0.0,
      thumbnail: TImages.productImage52,
      images: [TImages.productImage52],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['iphone', '14', 'pro', '512gb'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00039
    ProductModel(
      id: '00039',
      title: 'Iphone 14 white 512gb',
      lowerTitle: 'iphone 14 white 512gb',
      description: [
        {"insert": "This is a Product description for Iphone. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 999,
      salePrice: 0.0,
      thumbnail: TImages.productImage53,
      images: [TImages.productImage53],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['iphone', '14', 'white', '512gb'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: false,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00040
    ProductModel(
      id: '00040',
      title: 'Iphone 12, 4 Colors 128gb and 256gb',
      lowerTitle: 'iphone 12, 4 colors 128gb and 256gb',
      description: [
        {"insert": "This is a Product description for Iphone 12. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 950,
      salePrice: 800,
      thumbnail: TImages.productImage70,
      images: [
        TImages.productImage70,
        TImages.productImage71,
        TImages.productImage72,
        TImages.productImage73,
      ],
      productType: ProductType.variable,
      stock: 15,
      soldQuantity: 0,
      tags: ['iphone', '12', 'colors', '128gb', '256gb'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          // Color
          name: 'Color',
          values: ['Green', 'Red', 'Blue', 'Black'],
          isColorAttribute: true,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          // Storage
          name: 'Storage',
          values: ['128 gb', '256 gb'],
          isColorAttribute: false,
        ),
      ],
      variations: [
        ProductVariationModel(
          id: '1',
          stock: 16,
          price: 400,
          salePrice: 350,
          image: TImages.productImage70,
          description: [
            {"insert": "This is a Product description for Iphone 12. There are more things that can be added but i am just practicing and nothing else."}
          ].toString(),
          attributeValues: {'Color': 'Red', 'Storage': '128 gb'},
          sku: 'ABR4568-1',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 450,
          salePrice: 0.0,
          image: TImages.productImage70,
          description: "".toString(),
          attributeValues: {'Color': 'Red', 'Storage': '256 gb'},
          sku: 'ABR4568-2',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '3',
          stock: 14,
          price: 470,
          salePrice: 0.0,
          image: TImages.productImage71,
          description: "".toString(),
          attributeValues: {'Color': 'Blue', 'Storage': '128 gb'},
          sku: 'ABR4568-3',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '4',
          stock: 13,
          price: 500,
          salePrice: 0.0,
          image: TImages.productImage71,
          description: "".toString(),
          attributeValues: {'Color': 'Blue', 'Storage': '256 gb'},
          sku: 'ABR4568-4',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '5',
          stock: 12,
          price: 650,
          salePrice: 0.0,
          image: TImages.productImage72,
          description: "".toString(),
          attributeValues: {'Color': 'Green', 'Storage': '128 gb'},
          sku: 'ABR4568-5',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '6',
          stock: 12,
          price: 650,
          salePrice: 0.0,
          image: TImages.productImage72,
          description: "".toString(),
          attributeValues: {'Color': 'Green', 'Storage': '256 gb'},
          sku: 'ABR4568-6',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '7',
          stock: 11,
          price: 800,
          salePrice: 0.0,
          image: TImages.productImage73,
          description: "".toString(),
          attributeValues: {'Color': 'Black', 'Storage': '128 gb'},
          sku: 'ABR4568-7',
          soldQuantity: 0,
        ),
        ProductVariationModel(
          id: '8',
          stock: 11,
          price: 800,
          salePrice: 0.0,
          image: TImages.productImage73,
          description: "".toString(),
          attributeValues: {'Color': 'Black', 'Storage': '256 gb'},
          sku: 'ABR4568-8',
          soldQuantity: 0,
        ),
      ],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),

// Product 00008
    ProductModel(
      id: '00008',
      title: 'APPLE iPhone 8 (Black, 64 GB)',
      lowerTitle: 'apple iphone 8 (black, 64 gb)',
      description: [
        {"insert": "This is a Product description for iphone 8. There are more things that can be added but i am just practicing and nothing else."}
      ].toString(),
      sku: 'ABR4568',
      price: 480,
      salePrice: 380,
      thumbnail: TImages.productImage14,
      images: [
        TImages.productImage15,
        TImages.productImage16,
        TImages.productImage17,
        TImages.productImage14,
      ],
      productType: ProductType.simple,
      stock: 15,
      soldQuantity: 0,
      tags: ['apple', 'iphone', '8', 'black', '64gb'],
      attributes: [
        ProductAttributeModel(
          id: '1',
          attributeId: 'baQDeu1mZmc0ipGCh9vc',
          name: 'Size',
          values: ['EU34', 'EU32'],
          isColorAttribute: false,
        ),
        ProductAttributeModel(
          id: '2',
          attributeId: 'jve1tbtbjTetOYK9MF46',
          name: 'Color',
          values: ['Green', 'Red', 'Blue'],
          isColorAttribute: true,
        ),
      ],
      variations: [],
      isFeatured: true,
      isRecommended: false,
      isActive: true,
      isDraft: false,
      isDeleted: false,
      createdBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      createdAt: DateTime.now(),
      updatedBy: 'Tjb2vLqK2QfipFcycOanEt2hxnN2',
      updatedAt: DateTime.now(),
      isOutOfStock: false,
      onSale: true,
      saleStartDate: null,
      saleEndDate: null,
    ),
  ];

  /// -- Sorting Filters for search
  static final sortingFilters = [
    SortFilterModel(id: '1', name: 'Name'),
    SortFilterModel(id: '2', name: 'Lowest Price'),
    SortFilterModel(id: '3', name: 'Most Popular'),
    SortFilterModel(id: '4', name: 'Highest Price'),
    SortFilterModel(id: '5', name: 'Newest'),
    SortFilterModel(id: '6', name: 'Most Suitable'),
  ];

  /// -- Product Reviews
// static final List<ReviewModel> productReviews = [
//   ReviewModel(
//     id: '01',
//     userId: '001',
//     userName: 'John Doe',
//     rating: 4.5,
//     timestamp: DateTime.now(),
//     companyTimestamp: DateTime.now(),
//     userImageUrl: TImages.userProfileImage2,
//     comment: 'The user interface of the app is quite intuitive. I was able to navigate and make purchases seamlessly. Great job!',
//     companyComment:
//     'Thank you for your kind words, John! We are delighted to hear about your smooth experience with the app. We always strive to offer an intuitive interface for our users. Stay tuned for more updates!',
//   ),
//   ReviewModel(
//     id: '02',
//     userId: '002',
//     userName: 'Sophia Wilson',
//     rating: 3.5,
//     timestamp: DateTime.now(),
//     companyTimestamp: DateTime.now(),
//     userImageUrl: TImages.userProfileImage1,
//     comment:
//     'I am genuinely impressed with the app design and the variety of products available. The filter and sort features have made shopping so much easier for me!',
//     companyComment:
//     'Thank you so much, Sophia! We are thrilled to hear you are enjoying the app and finding the features useful. Our goal is to make your shopping experience as efficient and pleasant as possible. Keep exploring, and happy shopping!',
//   ),
//   ReviewModel(
//     id: '03',
//     userId: '003',
//     userName: 'Alex Brown',
//     rating: 5,
//     timestamp: DateTime.now(),
//     companyTimestamp: DateTime.now(),
//     userImageUrl: TImages.userProfileImage3,
//     comment: 'The app is pretty fast, and the product recommendations are on point! I would love to see more features in the future.',
//     companyComment:
//     'Thanks for the feedback, Alex! We are thrilled to hear you enjoyed the speed and recommendations. We are constantly working on introducing new features, so keep an eye out for the next update!',
//   ),
// ];
}

class SortFilterModel {
  String id;
  String name;

  SortFilterModel({required this.id, required this.name});
}
