name: cuex_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+22

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  geocoding: ^5.0.0
  geolocator: ^14.0.2
  gap: ^3.0.1
  dio: ^5.7.0
  uuid: ^4.5.0
  http: ^1.3.0
  intl: ^0.20.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  logger: ^2.5.0
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  shared_preferences: ^2.5.5

  url_launcher: ^6.3.1
  connectivity_plus: ^7.3.1
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^2.0.1
  country_code_picker: ^3.1.0
  otp_text_field: ^1.1.3
  animate_do: ^5.1.0
  share_plus: ^13.3.0
  badges: ^3.1.2
  wakelock_plus: ^1.2.10
  firebase_database: ^12.4.6

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  firebase_messaging: ^16.4.3
  cloud_firestore: ^6.7.1
  firebase_storage: ^13.4.5
  google_sign_in: ^6.2.1
  cloud_functions: ^6.3.5
  firebase_crashlytics: ^5.2.6
  firebase_analytics: ^12.4.5

  google_places_flutter: ^2.0.9
  path_provider: ^2.1.4
  permission_handler: ^12.0.3
  percent_indicator: ^4.2.1
  google_fonts: ^8.2.0
  battery_plus: ^7.1.1
  freezed_annotation: ^3.1.0

  qr_flutter: ^4.1.0
  chewie: ^1.8.5
  video_player: ^2.9.2
  youtube_explode_dart: ^3.1.0
  flutter_local_notifications: ^22.2.0
  file_picker: ^12.0.0-beta.7
  device_info_plus: ^13.2.0
  lucide_icons: ^0.257.0
  lucide_icons_flutter: ^3.1.0
  firebase_app_check: ^0.4.5+2
  sms_autofill: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/cuex_logo_final.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/

    - assets/images/animations/
    - assets/logos/logo.png
    - assets/images/on_boarding_images/
    - assets/logos/snooker.json
    - assets/logos/Traingle.json
    - assets/logos/logo.json
    - assets/logos/loader.json
    - assets/logos/favicon.png
    - assets/logos/google-icon.png
    - assets/videos/livestreaming.mp4
    - assets/images/streaming/cue_cam.png
    - assets/videos/intro.webm
    - assets/logos/live.json
    - assets/sports/snooker.png
    - assets/images/sports/snooker.png
    - assets/images/sports/pool.png
    - assets/images/sports/billiard.png
    - assets/images/sports/heyball.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800