// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfbjUENoOkj5tza6CqYxh3luFKJro167s',
    appId: '1:488636506968:web:35a89ed00cde122c373b2d',
    messagingSenderId: '488636506968',
    projectId: 'cuex-ab44c',
    authDomain: 'cuex-ab44c.firebaseapp.com',
    storageBucket: 'cuex-ab44c.firebasestorage.app',
    measurementId: 'G-QBQP4G6TJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSo82Tko2Hc42EEuH1GG_7t0DQ9DZZE6A',
    appId: '1:488636506968:android:3d51631bd2fa2f16373b2d',
    messagingSenderId: '488636506968',
    projectId: 'cuex-ab44c',
    storageBucket: 'cuex-ab44c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4y2lPS7Q4iQopNX4yxqqLInjUY-zoigM',
    appId: '1:488636506968:ios:175954890fe79773373b2d',
    messagingSenderId: '488636506968',
    projectId: 'cuex-ab44c',
    storageBucket: 'cuex-ab44c.firebasestorage.app',
    androidClientId: '488636506968-24rdbsgb1i63gm62jej0reb2o169bo8o.apps.googleusercontent.com',
    iosClientId: '488636506968-bjm770jfl4ccpvhb0vtfiv0h33jgi8bl.apps.googleusercontent.com',
    iosBundleId: 'com.codingwitht.ecommerce.tstoreEcommerceApp',
  );
}